# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_auto_20200226_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hood',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
